import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components';
import BlogListItem from '../components/BlogListItem';
import Container from '../components/Container';
import Header from "../components/Header";

const PageTitle = styled.h1`
  padding-top: 120px;
`

const BlogList: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Anasayfa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/suit.png" />
        <link
          rel="preload"
          href="/fonts/Poppins-Black.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Poppins-BlackItalic.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Poppins-Bold.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Poppins-Thin.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Poppins-Medium.ttf"
          as="font"
          crossOrigin=""
        />
      </Head>
      <Header />
      <main>
        <Container>
          <PageTitle>Blog</PageTitle>
          <BlogListItem title="UI interaction of the week" date={new Date()} tags="Javascript" description="Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet"/>
          <BlogListItem title="React Native Nedir" date={new Date()} tags="Javascript" description="Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet"/>
          <BlogListItem title="Neden React" date={new Date()} tags="Javascript" description="Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet"/>
          <BlogListItem title="Heyhat, Ben bu isi kiviririm" date={new Date()} tags="Javascript" description="Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet"/>
        </Container>
      </main>
    </div>
  )
}

export default BlogList;

