import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components';
import BlogListItem from '../components/BlogListItem';
import Container from '../components/Container';
import Header from "../components/Header";
import { getSortedPostsData } from '../lib/posts'

const PageTitle = styled.h1`
  padding-top: 120px;
`

interface PostData{
  id: string;
  date: string;
  title: string;
}

interface BlogListProps{
  allPostsData: Array<PostData>
}

const BlogList: NextPage<BlogListProps> = ({allPostsData}) => {
  return (
    <>
      <Head>
        <title>Bloglarım</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/suit.png" />
        <link
          rel="preload"
          href="/fonts/Poppins-Black.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Poppins-BlackItalic.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Poppins-Bold.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Poppins-Thin.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Poppins-Medium.ttf"
          as="font"
          crossOrigin=""
        />
      </Head>
      <Header />
      <main>
        <Container>
          <PageTitle>Blog</PageTitle>
          {allPostsData.map(({id, title, date}) => (
            <BlogListItem href={`blogs/${id}`} key={id} title={title} date={date} tags="Javascript" description="Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet"/>
          ))}
        </Container>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const allPostsData = getSortedPostsData()
  return {
    props: {
      allPostsData
    }
  }
}

export default BlogList;


