import type { NextPage } from 'next'
import Head from 'next/head'
import Header from "../components/Header";
import Promotion from '../components/Promotion';
import CountSection from '../components/CountSection';
import RecentProjects from '../components/RecentProjects';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Anasayfa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/fonts/Poppins-Black.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Poppins-BlackItalic.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Poppins-Bold.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Poppins-Thin.ttf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/Poppins-Medium.ttf"
          as="font"
          crossOrigin=""
        />
      </Head>
      <Header />
      <main>
        <Promotion></Promotion>
        <CountSection></CountSection>
        <RecentProjects></RecentProjects>
      </main>
    </div>
  )
}

export default Home
